apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka
  serviceName: {{ .Release.Name }}-kafka
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka
    spec:
      containers:
          - name: kafka
            image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
            imagePullPolicy: "{{ .Values.kafka.image.pullPolicy }}"
            ports:
              - containerPort: 9092
                name: client
            env:
              - name: KAFKA_ADVERTISED_HOST_NAME
                value: "{{.values.hosts.host}}"
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: "zookeeper:2181"
            livenessProbe:
              tcpSocket:
                port: 9092
              initialDelaySeconds: 30
              timeoutSeconds: 5
            readinessProbe:
              tcpSocket:
                port: 9092
              initialDelaySeconds: 5
              timeoutSeconds: 1
