apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app: {{ .Release.Name }}-zookeeper
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  ports:
    - name: client
      port: 9092
      targetPort: 9092
  selector:
    app: {{ .Release.Name }}-kafka
  clusterIP: None