import ca.uhn.fhir.context.FhirContext;
import org.hl7.fhir.instance.model.api.IBaseBundle;
import org.hl7.fhir.instance.model.api.IBaseResource;
import org.hl7.fhir.r4.model.Bundle;
import org.hl7.fhir.r4.model.Observation;

public class FhirDataParser {
    public static void main(String[] args) {
        String fhirBundleJson = "{...}"; // Your FHIR Bundle JSON here

        // Create an instance of FhirContext
        FhirContext fhirContext = FhirContext.forR4();

        // Parse the FHIR Bundle JSON
        IBaseBundle bundle = fhirContext.newJsonParser().parseResource(fhirBundleJson);

        if (bundle instanceof Bundle) {
            Bundle fhirBundle = (Bundle) bundle;

            // Extract the MDCX_HEART_RATE_PFC_FHR1 data
            for (Bundle.BundleEntryComponent entry : fhirBundle.getEntry()) {
                IBaseResource resource = entry.getResource();
                if (resource instanceof Observation) {
                    Observation observation = (Observation) resource;
                    for (Observation.ObservationComponentComponent component : observation.getComponent()) {
                        String codeDisplay = component.getCode().getCodingFirstRep().getDisplay();
                        if (codeDisplay.equals("MDCX_HEART_RATE_PFC_FHR1")) {
                            String data = component.getValueSampledData().getData();
                            System.out.println("MDCX_HEART_RATE_PFC_FHR1 Data: " + data);
                        }
                    }
                }
            }
        }
    }
}
