// Parse the FHIR Bundle JSON
        Gson gson = new Gson();
        JsonObject bundle = gson.fromJson(fhirBundleJson, JsonObject.class);

        // Extract the MDCX_UTERINE_ACTIVITY_PFC data
        JsonArray entries = bundle.getAsJsonArray("entry");
        if (entries != null && entries.size() > 0) {
            JsonObject firstEntry = entries.get(0).getAsJsonObject();
            JsonObject resource = firstEntry.getAsJsonObject("resource");
            JsonArray components = resource.getAsJsonArray("component");
            if (components != null && components.size() > 0) {
                JsonObject component = components.get(0).getAsJsonObject();
                JsonObject valueSampledData = component.getAsJsonObject("valueSampledData");
                String data = valueSampledData.get("data").getAsString();
                System.out.println("MDCX_UTERINE_ACTIVITY_PFC data: " + data);
            }
        }
